---
- name: Ensure Puppet configuration directory exists
  ansible.builtin.file:
    path: "{{ puppet_conf_dir }}"
    state: directory
    owner: puppet
    group: puppet
    mode: "0755"

- name: Configure Puppet Server puppet.conf
  ansible.builtin.template:
    src: puppet.conf.j2
    dest: "{{ puppet_conf_file }}"
    owner: puppet
    group: puppet
    mode: "0644"
  notify:
    - Restart puppetserver

- name: Configure Puppet Server JVM
  ansible.builtin.lineinfile:
    path: /etc/default/puppetserver
    regexp: '^JAVA_ARGS='
    line: >-
      JAVA_ARGS="{% if puppetserver_java_min_heap %}-Xms{{ puppetserver_java_min_heap }} {% endif %}{% if puppetserver_java_max_heap %}-Xmx{{ puppetserver_java_max_heap }} {% endif %}{% for arg in puppetserver_java_extra_args %}{{ arg }}{% if not loop.last %} {% endif %}{% endfor %}"
    state: present
  when:
    - puppetserver_java_min_heap | length > 0
      or puppetserver_java_max_heap | length > 0
  notify:
    - Restart puppetserver
