---
- name: Remove obsolete Puppet Server systemd override
  ansible.builtin.file:
    path: /etc/systemd/system/puppetserver.service.d
    state: absent
  notify:
    - Restart puppetserver

- name: Ensure Puppet Server is enabled and running
  ansible.builtin.systemd:
    name: "{{ puppetserver_service_name }}"
    enabled: true
    state: started
    daemon_reload: true
