---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: puppet
      vars:
        puppetserver_certname: puppet
        puppetserver_java_min_heap: "256m"
        puppetserver_java_max_heap: "512m"
        puppet_manage_command_symlink: true
