---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Verify Puppet Server package
      ansible.builtin.assert:
        that:
          - "'puppetserver' in ansible_facts.packages"
        fail_msg: "Puppet Server package is not installed"

    - name: Verify Puppet Agent package
      ansible.builtin.assert:
        that:
          - "'puppet-agent' in ansible_facts.packages"
        fail_msg: "Puppet Agent package is not installed"

    - name: Wait for Puppet Server service
      ansible.builtin.service_facts:
      register: puppet_service_facts
      retries: 30
      delay: 2
      until:
        - "'puppetserver.service' in puppet_service_facts.ansible_facts.services"
        - >-
          puppet_service_facts.ansible_facts.services['puppetserver.service'].state
          == 'running'

    - name: Verify Puppet Server service
      ansible.builtin.assert:
        that:
          - puppet_service_facts.ansible_facts.services['puppetserver.service'].state == 'running'
          - puppet_service_facts.ansible_facts.services['puppetserver.service'].status == 'enabled'
        fail_msg: "Puppet Server service is not running and enabled"

    - name: Wait for Puppet Server port
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8140
        state: started
        timeout: 120
        delay: 2
